import Board from "@/components/board";
import { db } from "@/db/drizzle";
import { boards } from "@/db/schema";
import { eq } from "drizzle-orm";
import { Metadata } from "next";
import React from "react";

type Props = {
	params: {
		id: string;
	};
};

export const metadata: Metadata = {
	title: "Create Next Appaf",
	description: "Generated by create next app",
};

export default async function SingleBoard({ params }: Props) {
	const { id } = await params;
	// const data = await db.query.boards.findFir

	return (
		<div>
			<Board />
		</div>
	);
}
