import { BoardType, ColumnType } from "@/app/types";
import { auth } from "@/auth";
import Board from "@/components/board";
import { Metadata } from "next";
import { redirect } from "next/navigation";
import React from "react";
import { getBoardWithColumnsAndTasks } from "../actions";

type Props = {
	params: Promise<{ id: string }>;
};

export const metadata: Metadata = {
	title: "Create Next Appaf",
	description: "Generated by create next app",
};

export default async function SingleBoard({ params }: Props) {
	const session = await auth();
	if (!session?.user) {
		redirect("/sign-in");
	}
	const userId = session?.user?.id as string;
	const { id: boardId } = await params;
	const boardData = await getBoardWithColumnsAndTasks(boardId, userId);

	const board: BoardType = {
		id: boardData?.data?.id ?? "",
		boardName: boardData?.data?.boardName ?? "",
		columns: (boardData?.data?.columns as ColumnType[]) ?? [],
	};

	return (
		<div>
			<Board boardId={boardId} userId={userId} board={board} />
		</div>
	);
}
